name: deploy-cloudrun Integration

on:
  push:
    paths:
    - 'deploy-cloudrun/**'
    - '.github/workflows/deploy-cloudrun-it.yml'
  pull_request:
    paths:
    - 'deploy-cloudrun/**'
    - '.github/workflows/deploy-cloudrun-it.yml'

jobs:
  envVars:
    name: with Env Vars
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      working-directory: deploy-cloudrun
      run: |-
        npm install
        npm run build
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_JSON }}
        image: gcr.io/cloudrun/hello
        service: test-envvars
        env_vars: TEST_ENV=TEST_VAR
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloudrun
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master # Set up ADC to make authenticated request to service
      with:
        service_account_key: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        export_default_credentials: true
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy.outputs.url }}
        ENV: TEST_ENV=TEST_VAR
    - id: deploy2
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_JSON }}
        image: gcr.io/cloudrun/hello
        service: test-envvars
        env_vars: TEST_ENV2=TEST_VAR2
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy2.outputs.url }}
        SERVICE: test-envvars
        ENV: TEST_ENV=TEST_VAR,TEST_ENV2=TEST_VAR2

  yaml:
    name: with YAML metadata
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      working-directory: deploy-cloudrun
      run: |-
        npm install
        npm run build
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_JSON }}
        metadata: ./deploy-cloudrun/tests/unit/service.basic.yaml
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloudrun
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master # Set up ADC to make authenticated request to service
      with:
        service_account_key: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        export_default_credentials: true
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy.outputs.url }}

  metadata:
    name: with full YAML metada
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - id: build
      name: Build dist
      working-directory: deploy-cloudrun
      run: |-
        npm install
        npm run build
    - id: deploy
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_JSON }}
        metadata: ./deploy-cloudrun/tests/unit/service.full.yaml
    - uses: actions/setup-node@master
      with:
        node-version: 12.x
    - run: npm install
      working-directory: ./deploy-cloudrun
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master # Set up ADC to make authenticated request to service
      with:
        service_account_key: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_B64 }}
        export_default_credentials: true
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy.outputs.url }}
        PARAMS: "{\"cpu\": 2,\"memory\": \"1Gi\", \"containerConcurrency\": 20}"
        ANNOTATIONS: "{\"run.googleapis.com/cloudsql-instances\": \"1:2:3\"}"
        LABELS: "{\"test_label\": \"test_value\"}"
    - id: deploy2
      uses: ./deploy-cloudrun
      with:
        credentials: ${{ secrets.DEPLOY_CLOUDRUN_SA_KEY_JSON }}
        image: gcr.io/cloudrun/hello
        service: test-full-yaml
    - name: integration tests
      run: npm run e2e-tests
      working-directory: ./deploy-cloudrun
      env:
        URL: ${{ steps.deploy2.outputs.url }}
        SERVICE: test-full-yaml
        PARAMS: "{\"cpu\": 2,\"memory\": \"1Gi\", \"containerConcurrency\": 20}"
        ANNOTATIONS: "{\"run.googleapis.com/cloudsql-instances\": \"1:2:3\"}"
        LABELS: "{\"test_label\": \"test_value\"}"
